/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiveRouteImport } from './routes/dive'
import { Route as OceanRouteImport } from './routes/ocean'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiveRoute = DiveRouteImport.update({
  id: '/dive',
  path: '/dive',
  getParentRoute: () => rootRouteImport,
} as any)
const OceanRoute = OceanRouteImport.update({
  id: '/ocean',
  path: '/ocean',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dive': typeof DiveRoute
  '/ocean': typeof OceanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dive': typeof DiveRoute
  '/ocean': typeof OceanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dive': typeof DiveRoute
  '/ocean': typeof OceanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dive' | '/ocean'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dive' | '/ocean'
  id: '__root__' | '/' | '/dive' | '/ocean'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiveRoute: typeof DiveRoute
  OceanRoute: typeof OceanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dive': {
      id: '/dive'
      path: '/dive'
      fullPath: '/dive'
      preLoaderRoute: typeof DiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocean': {
      id: '/ocean'
      path: '/ocean'
      fullPath: '/ocean'
      preLoaderRoute: typeof OceanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiveRoute: DiveRoute,
  OceanRoute: OceanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
